# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Opal Sea Racing
email: vbrasseur+opal (at) gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  a comprehensive collection of tide, sail, and regatta tools to optimize your sailing adventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: val75429282
github_username:  valgit
google_analytics: UA-NNNNNNNN-N
copyright: "© 2023 Opal Sea Racing."

# Build settings
#theme: minima
#remote_theme: chrisrhymes/mere-blog-theme
#https://github.com/mmistakes/jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed  
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist  
  - jemoji
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
paginate: 5
paginate_path: /page:num/
search: true

author:
  name: Valery
  twitter: val75429282

